### ISSUE TITLE
Unable to resolve module  ./src/Timetable

### ISSUE THREAD

**Issue by caolong0204** [dorkyboi/react-native-calendar-timetable#5] opened 2022-05-05 03:13 UTC
i don't know why, but i always get this error when building app after install lib.
error: Error: Unable to resolve module ./src/Timetable from /Users/.../node_modules/react-native-calendar-timetable/index.js: 
<img width="331" alt="Screen Shot 2022-05-05 at 10 09 31" src="https://user-images.githubusercontent.com/66582805/166858642-c7e0799a-6d88-4c59-adc1-b70b941bc356.png">
How to implement your lib?

**Comment by GeorgeHop** [comment] 2022-05-06 07:41
Hi @caolong0204 thank you for using our lib! May I ask you about screenshots of code where you using our library, with imports?! It will give us possibility to resolve your issue so fast as we can!

**Comment by dorkyboi** [comment] 2022-05-06 14:24
Hey @caolong0204, I have tested it in a new app made with `expo init` and found no issues.
We could really use more info on how your project is setup (ideally, an expo snack, but i think steps-to-reproduce would also work).

Here's how i did it:
```javascript
// components/MyPage.jsx
import Timetable from "react-native-calendar-timetable";

function MyPage() {
    return <Timetable date={new Date()}/>;
}

export default MyPage;
```
```javascript
// App.js
import {View} from "react-native";
import MyPage from "./components/MyPage";

export default function App() {
  return (
    <View>
      <MyPage/>
    </View>
  );
}

```

**Comment by NatakuZ** [comment] 2022-05-27 15:56
Hi , when i installed the library , i found this error. The problem is that : metro can't resolve the jsx file in default config.
to fix this you have to add in metro.config.js  this lines

`module.exports = {
  resolver: {

   sourceExts: ['jsx','js','ts','tsx']
  },` 
  after this I cleaned the cache and the app worked.

**Comment by GeorgeHop** [comment] 2022-05-31 08:15
We will prepare fix for this shortly.

**Comment by GeorgeHop** [comment] 2022-05-31 08:22
Fix for this issue -> https://github.com/dorkyboi/react-native-calendar-timetable/commit/d6c1f72185ab6670b7d991b4f714085d138d5bae

**Closed as completed by GeorgeHop** 2022-05-31 08:22 UTC
